import type { Locale } from '@/app/i18n/messages';

const CHANNELS_COPY_BY_LOCALE = {
  es: {
    title: 'Canales',
    subtitle: 'Gestiona tus canales de YouTube conectados',
    create: 'Anadir canal',
    emptyTitle: 'No hay canales',
    emptySubtitle: 'Conecta tu primer canal de YouTube para comenzar',
    emptyAction: 'Anadir canal',
    statusConnected: 'Conectado',
    statusPending: 'Pendiente',
    createdAt: 'Anadido:',
    viewAnalytics: 'Ver analytics ->',
    edit: 'Editar',
    delete: 'Eliminar',
    modalTitleCreate: 'Anadir canal',
    modalTitleEdit: 'Editar canal',
    guide: {
      connected: 'Canal conectado. Ya puedes empezar el flujo.',
      created: 'Canal creado. Siguiente paso: activar tu flujo.',
      step1: '1) Selecciona el canal activo.',
      step2: '2) Abre AI Studio y genera ideas evergreen.',
      step3: '3) Continua con guion y SEO.',
      goToAi: 'Ir a AI Studio',
      close: 'Cerrar',
    },
    social: {
      connecting: 'Conectando...',
      connectYoutube: 'Conectar YouTube',
      popupBlocked: 'No se pudo abrir la ventana de Google. Revisa el bloqueador de popups.',
      connected: 'YouTube conectado',
      connectFailed: 'No se pudo completar la conexion. Reintenta.',
    },
    actions: {
      channelUpdated: 'Canal actualizado',
      channelCreated: 'Canal creado',
      channelDeleted: 'Canal eliminado',
      retry: 'Reintentar',
      subsSuffix: 'subs',
    },
    errors: {
      load: 'Error al cargar canales',
      unknown: 'Error desconocido',
      create: 'Error al crear canal',
      delete: 'Error al eliminar canal',
      deleteConfirmPrefix: 'Eliminar canal',
    },
    form: {
      name: 'Nombre del canal',
      youtubeId: 'YouTube Channel ID',
      youtubeHelp: 'Puedes encontrarlo en la URL de tu canal de YouTube',
      placeholderName: 'Mi canal de YouTube',
      placeholderId: 'UCxxxxxxxxxxxxx',
    },
    cancel: 'Cancelar',
    submitCreate: 'Crear canal',
    submitEdit: 'Guardar cambios',
    submittingCreate: 'Creando...',
    submittingEdit: 'Guardando...',
    loading: 'Cargando canales...',
  },
  en: {
    title: 'Channels',
    subtitle: 'Manage your connected YouTube channels',
    create: 'Add channel',
    emptyTitle: 'No channels yet',
    emptySubtitle: 'Connect your first YouTube channel to get started',
    emptyAction: 'Add channel',
    statusConnected: 'Connected',
    statusPending: 'Pending',
    createdAt: 'Added:',
    viewAnalytics: 'View analytics ->',
    edit: 'Edit',
    delete: 'Delete',
    modalTitleCreate: 'Add channel',
    modalTitleEdit: 'Edit channel',
    guide: {
      connected: 'Channel connected. You can start the flow now.',
      created: 'Channel created. Next step: activate your flow.',
      step1: '1) Select the active channel.',
      step2: '2) Open AI Studio and generate evergreen ideas.',
      step3: '3) Continue with script and SEO.',
      goToAi: 'Go to AI Studio',
      close: 'Close',
    },
    social: {
      connecting: 'Connecting...',
      connectYoutube: 'Connect YouTube',
      popupBlocked: 'Could not open Google window. Check your popup blocker.',
      connected: 'YouTube connected',
      connectFailed: 'Could not complete connection. Retry.',
    },
    actions: {
      channelUpdated: 'Channel updated',
      channelCreated: 'Channel created',
      channelDeleted: 'Channel deleted',
      retry: 'Retry',
      subsSuffix: 'subs',
    },
    errors: {
      load: 'Error loading channels',
      unknown: 'Unknown error',
      create: 'Error creating channel',
      delete: 'Error deleting channel',
      deleteConfirmPrefix: 'Delete channel',
    },
    form: {
      name: 'Channel name',
      youtubeId: 'YouTube Channel ID',
      youtubeHelp: 'You can find it in your YouTube channel URL',
      placeholderName: 'My YouTube channel',
      placeholderId: 'UCxxxxxxxxxxxxx',
    },
    cancel: 'Cancel',
    submitCreate: 'Create channel',
    submitEdit: 'Save changes',
    submittingCreate: 'Creating...',
    submittingEdit: 'Saving...',
    loading: 'Loading channels...',
  },
} as const;

export function getChannelsCopy(locale: Locale) {
  return CHANNELS_COPY_BY_LOCALE[locale] ?? CHANNELS_COPY_BY_LOCALE.es;
}

export const CHANNELS_COPY = getChannelsCopy('es');
