export const CHANNELS_COPY = {
  title: 'Canales',
  subtitle: 'Gestiona tus canales de YouTube conectados',
  create: 'Anadir canal',
  emptyTitle: 'No hay canales',
  emptySubtitle: 'Conecta tu primer canal de YouTube para comenzar',
  emptyAction: 'Anadir canal',
  statusConnected: 'Conectado',
  statusPending: 'Pendiente',
  createdAt: 'Anadido:',
  viewAnalytics: 'Ver Analytics →',
  edit: 'Editar',
  delete: 'Eliminar',
  modalTitleCreate: 'Anadir Canal',
  modalTitleEdit: 'Editar Canal',
  form: {
    name: 'Nombre del Canal',
    youtubeId: 'YouTube Channel ID',
    youtubeHelp: 'Puedes encontrarlo en la URL de tu canal de YouTube',
    placeholderName: 'Mi Canal de YouTube',
    placeholderId: 'UCxxxxxxxxxxxxx',
  },
  cancel: 'Cancelar',
  submitCreate: 'Crear Canal',
  submitEdit: 'Guardar cambios',
  submittingCreate: 'Creando...',
  submittingEdit: 'Guardando...',
  loading: 'Cargando canales...',
};
