export const IDEAS_COPY = {
  title: 'Ideas',
  subtitle: 'Apunta y gestiona tus ideas para videos',
  channelPrefix: 'Canal:',
  emptyTitle: 'No hay ideas todavia',
  emptySubtitle: 'Apunta tu primera idea para un video.',
  new: 'Nueva Idea',
  create: 'Crear idea',
  edit: 'Editar',
  delete: 'Eliminar',
  deleteTitle: 'Eliminar idea',
  deleteConfirm: '¿Seguro que quieres eliminar',
  deleteIrreversible: 'Esta accion no se puede deshacer.',
  cancel: 'Cancelar',
  save: 'Guardar',
  creating: 'Creando...',
  saving: 'Guardando...',
  deleting: 'Eliminando...',
  list: {
    showMore: 'Ver mas',
    showLess: 'Ver menos',
  },
  form: {
    title: 'Titulo',
    description: 'Descripcion',
    channel: 'Canal',
    priority: 'Prioridad (0-10)',
    tags: 'Tags (separados por coma)',
    noChannel: 'Sin canal',
    placeholderTitle: 'Idea para video...',
    placeholderDescription: 'Detalles de la idea...',
    placeholderTags: 'seo, video, tutorial',
  },
  toasts: {
    created: 'Idea creada',
    updated: 'Idea actualizada',
    deleted: 'Idea eliminada',
    statusUpdated: 'Estado actualizado',
    error: 'Error',
  },
};
