import type { Locale } from '@/app/i18n/messages';

const IDEAS_COPY_BY_LOCALE = {
  es: {
    title: 'Ideas',
    subtitle: 'Apunta y gestiona tus ideas para videos',
    channelPrefix: 'Canal:',
    emptyTitle: 'No hay ideas todavia',
    emptySubtitle: 'Apunta tu primera idea para un video.',
    new: 'Nueva idea',
    create: 'Crear idea',
    edit: 'Editar',
    delete: 'Eliminar',
    deleteTitle: 'Eliminar idea',
    deleteConfirm: '¿Seguro que quieres eliminar',
    deleteIrreversible: 'Esta accion no se puede deshacer.',
    cancel: 'Cancelar',
    save: 'Guardar',
    creating: 'Creando...',
    saving: 'Guardando...',
    deleting: 'Eliminando...',
    controls: {
      channel: 'Canal',
      allChannels: 'Todos los canales',
      selectedCount: 'seleccionadas',
      approve: 'Aprobar',
      archive: 'Archivar',
      clear: 'Limpiar',
      retry: 'Reintentar',
    },
    ideaCard: {
      select: 'Seleccionar',
      selectAriaPrefix: 'Seleccionar idea',
      pipelineRunning: 'Pipeline...',
      pipelineAi: 'Pipeline AI',
      scriptAi: 'Guion AI',
      completeIdea: 'Completar idea',
      useSelectedChannel: 'Usar canal seleccionado',
    },
    checklist: {
      title: 'Checklist para aprobar',
      promise: 'Promesa: “En este video vas a entender…”',
      bullets: 'Bullets: minimo 3 lineas con “-”',
      hook: 'Hook: 2 frases o 200 caracteres',
      promiseError: 'Falta promesa',
      bulletsError: 'Faltan bullets (min 3)',
      hookError: 'Falta hook (min 2 frases o 200 chars)',
    },
    list: {
      showMore: 'Ver mas',
      showLess: 'Ver menos',
    },
    form: {
      title: 'Titulo',
      description: 'Descripcion',
      channel: 'Canal',
      priority: 'Prioridad (0-10)',
      tags: 'Tags (separados por coma)',
      noChannel: 'Sin canal',
      placeholderTitle: 'Idea para video...',
      placeholderDescription: 'Promesa: En este video vas a entender ...\nBullets:\n- Punto 1\n- Punto 2\n- Punto 3\nHook: Escribe 2 frases o 200 caracteres...',
      placeholderTags: 'seo, video, tutorial',
    },
    toasts: {
      created: 'Idea creada',
      updated: 'Idea actualizada',
      deleted: 'Idea eliminada',
      statusUpdated: 'Estado actualizado',
      ideaNotReady: 'Idea no lista: completa promesa, bullets y hook',
      pipelineNeedsChannel: 'Selecciona un canal para ejecutar el pipeline',
      pipelineDone: 'Pipeline completado (guion + SEO)',
      pipelineError: 'Error al ejecutar pipeline',
      error: 'Error',
    },
    errors: {
      ideaNotReadyTitle: 'Faltantes para marcar como lista',
      loadIdeas: 'Error al cargar ideas',
      requestFailed: 'Solicitud fallida',
    },
  },
  en: {
    title: 'Ideas',
    subtitle: 'Capture and manage your video ideas',
    channelPrefix: 'Channel:',
    emptyTitle: 'No ideas yet',
    emptySubtitle: 'Capture your first idea for a video.',
    new: 'New idea',
    create: 'Create idea',
    edit: 'Edit',
    delete: 'Delete',
    deleteTitle: 'Delete idea',
    deleteConfirm: 'Are you sure you want to delete',
    deleteIrreversible: 'This action cannot be undone.',
    cancel: 'Cancel',
    save: 'Save',
    creating: 'Creating...',
    saving: 'Saving...',
    deleting: 'Deleting...',
    controls: {
      channel: 'Channel',
      allChannels: 'All channels',
      selectedCount: 'selected',
      approve: 'Approve',
      archive: 'Archive',
      clear: 'Clear',
      retry: 'Retry',
    },
    ideaCard: {
      select: 'Select',
      selectAriaPrefix: 'Select idea',
      pipelineRunning: 'Pipeline...',
      pipelineAi: 'AI Pipeline',
      scriptAi: 'AI Script',
      completeIdea: 'Complete idea',
      useSelectedChannel: 'Use selected channel',
    },
    checklist: {
      title: 'Approval checklist',
      promise: 'Promise: “In this video you will understand…”',
      bullets: 'Bullets: at least 3 lines with “-”',
      hook: 'Hook: 2 sentences or 200 characters',
      promiseError: 'Falta promesa',
      bulletsError: 'Faltan bullets (min 3)',
      hookError: 'Falta hook (min 2 frases o 200 chars)',
    },
    list: {
      showMore: 'Show more',
      showLess: 'Show less',
    },
    form: {
      title: 'Title',
      description: 'Description',
      channel: 'Channel',
      priority: 'Priority (0-10)',
      tags: 'Tags (comma separated)',
      noChannel: 'No channel',
      placeholderTitle: 'Video idea...',
      placeholderDescription: 'Promise: In this video you will understand ...\nBullets:\n- Point 1\n- Point 2\n- Point 3\nHook: Write 2 sentences or 200 characters...',
      placeholderTags: 'seo, video, tutorial',
    },
    toasts: {
      created: 'Idea created',
      updated: 'Idea updated',
      deleted: 'Idea deleted',
      statusUpdated: 'Status updated',
      ideaNotReady: 'Idea not ready: complete promise, bullets, and hook',
      pipelineNeedsChannel: 'Select a channel to run the pipeline',
      pipelineDone: 'Pipeline completed (script + SEO)',
      pipelineError: 'Error running pipeline',
      error: 'Error',
    },
    errors: {
      ideaNotReadyTitle: 'Missing items to mark as ready',
      loadIdeas: 'Error loading ideas',
      requestFailed: 'Request failed',
    },
  },
} as const;

export function getIdeasCopy(locale: Locale) {
  return IDEAS_COPY_BY_LOCALE[locale] ?? IDEAS_COPY_BY_LOCALE.es;
}

export type IdeasCopy = ReturnType<typeof getIdeasCopy>;
export const IDEAS_COPY = getIdeasCopy('es');
