import type { Locale } from '@/app/i18n/messages';

const SCRIPTS_COPY_BY_LOCALE = {
  es: {
    title: 'Guiones',
    subtitle: 'Crea y administra guiones para tus videos',
    new: 'Nuevo guion',
    emptyTitle: 'No hay guiones todavia',
    emptySubtitle: 'Escribe tu primer guion',
    create: 'Crear guion',
    edit: 'Editar',
    delete: 'Eliminar',
    deleteTitle: 'Eliminar guion',
    deleteWarning: 'Estas por eliminar',
    deleteIrreversible: 'Esta accion no se puede deshacer.',
    cancel: 'Cancelar',
    submitCreate: 'Crear guion',
    submitEdit: 'Guardar',
    submittingCreate: 'Creando...',
    submittingEdit: 'Guardando...',
    deleting: 'Eliminando...',
    wordCountLabel: 'palabras',
    ideaPrefix: 'De idea:',
    controls: {
      channel: 'Canal',
      allChannels: 'Todos los canales',
      selectedCount: 'seleccionados',
      toReview: 'A revision',
      approve: 'Aprobar',
      recorded: 'Grabado',
      clear: 'Limpiar',
      retry: 'Reintentar',
    },
    list: {
      showMore: 'Ver mas',
      showLess: 'Ver menos',
    },
    card: {
      selectPrefix: 'Seleccionar guion',
      select: 'Seleccionar',
      durationPrefix: '⏱ ~',
      pipelineRunning: 'Pipeline...',
      pipelinePublish: 'Pipeline Publicar',
      retention: 'Retencion',
      seoTitles: 'SEO + Titulos',
    },
    modal: {
      ideaIdOptional: 'Idea ID (opcional)',
      ideaIdPlaceholder: 'UUID de la idea',
      ideaByTitle: 'Idea (por titulo)',
      ideaByTitlePlaceholder: 'Buscar por titulo',
      quickChecklist: 'Checklist rapido',
      scoreLabel: 'Score',
      copyScript: 'Copiar guion',
      copyLink: 'Copiar link',
      downloadMd: 'Descargar .md',
      exportPdf: 'Exportar PDF',
      intro: 'Intro',
      body: 'Cuerpo',
      cta: 'CTA',
      outro: 'Outro',
      ok: 'ok',
      pending: 'pendiente',
    },
    fields: {
      title: 'Titulo',
      intro: 'Introduccion',
      body: 'Cuerpo',
      cta: 'Llamado a la accion',
      outro: 'Cierre',
    },
    placeholders: {
      title: 'Titulo del guion...',
      intro: 'Introduce el guion...',
      body: 'Desarrollo principal...',
      cta: 'Que accion quieres que tomen?',
      outro: 'Cierre y despedida...',
    },
    toasts: {
      created: 'Guion creado',
      updated: 'Guion actualizado',
      deleted: 'Guion eliminado',
      copiedScript: 'Guion copiado',
      copiedLink: 'Link copiado',
      copyScriptError: 'No se pudo copiar el guion',
      copyLinkError: 'No se pudo copiar el link',
      exportWindowError: 'No se pudo abrir la ventana de exportacion',
      pipelineNeedsChannel: 'Selecciona un canal para ejecutar el pipeline',
      pipelineDone: 'Pipeline completado (SEO + miniatura)',
      pipelineError: 'Error al ejecutar pipeline',
      error: 'Error',
    },
    errors: {
      save: 'Error al guardar guion',
      delete: 'Error al eliminar guion',
      load: 'Error al cargar guiones',
      requestFailed: 'Solicitud fallida',
    },
  },
  en: {
    title: 'Scripts',
    subtitle: 'Create and manage scripts for your videos',
    new: 'New script',
    emptyTitle: 'No scripts yet',
    emptySubtitle: 'Write your first script',
    create: 'Create script',
    edit: 'Edit',
    delete: 'Delete',
    deleteTitle: 'Delete script',
    deleteWarning: 'You are about to delete',
    deleteIrreversible: 'This action cannot be undone.',
    cancel: 'Cancel',
    submitCreate: 'Create script',
    submitEdit: 'Save',
    submittingCreate: 'Creating...',
    submittingEdit: 'Saving...',
    deleting: 'Deleting...',
    wordCountLabel: 'words',
    ideaPrefix: 'From idea:',
    controls: {
      channel: 'Channel',
      allChannels: 'All channels',
      selectedCount: 'selected',
      toReview: 'To review',
      approve: 'Approve',
      recorded: 'Recorded',
      clear: 'Clear',
      retry: 'Retry',
    },
    list: {
      showMore: 'Show more',
      showLess: 'Show less',
    },
    card: {
      selectPrefix: 'Select script',
      select: 'Select',
      durationPrefix: '⏱ ~',
      pipelineRunning: 'Pipeline...',
      pipelinePublish: 'Publish Pipeline',
      retention: 'Retention',
      seoTitles: 'SEO + Titles',
    },
    modal: {
      ideaIdOptional: 'Idea ID (optional)',
      ideaIdPlaceholder: 'Idea UUID',
      ideaByTitle: 'Idea (by title)',
      ideaByTitlePlaceholder: 'Search by title',
      quickChecklist: 'Quick checklist',
      scoreLabel: 'Score',
      copyScript: 'Copy script',
      copyLink: 'Copy link',
      downloadMd: 'Download .md',
      exportPdf: 'Export PDF',
      intro: 'Intro',
      body: 'Body',
      cta: 'CTA',
      outro: 'Outro',
      ok: 'ok',
      pending: 'pending',
    },
    fields: {
      title: 'Title',
      intro: 'Introduction',
      body: 'Body',
      cta: 'Call to action',
      outro: 'Closing',
    },
    placeholders: {
      title: 'Script title...',
      intro: 'Write the intro...',
      body: 'Main development...',
      cta: 'What action do you want viewers to take?',
      outro: 'Closing and farewell...',
    },
    toasts: {
      created: 'Script created',
      updated: 'Script updated',
      deleted: 'Script deleted',
      copiedScript: 'Script copied',
      copiedLink: 'Link copied',
      copyScriptError: 'Could not copy script',
      copyLinkError: 'Could not copy link',
      exportWindowError: 'Could not open export window',
      pipelineNeedsChannel: 'Select a channel to run the pipeline',
      pipelineDone: 'Pipeline completed (SEO + thumbnail)',
      pipelineError: 'Error running pipeline',
      error: 'Error',
    },
    errors: {
      save: 'Error saving script',
      delete: 'Error deleting script',
      load: 'Error loading scripts',
      requestFailed: 'Request failed',
    },
  },
} as const;

export function getScriptsCopy(locale: Locale) {
  return SCRIPTS_COPY_BY_LOCALE[locale] ?? SCRIPTS_COPY_BY_LOCALE.es;
}

export type ScriptsCopy = ReturnType<typeof getScriptsCopy>;
export const SCRIPTS_COPY = getScriptsCopy('es');
