export const SCRIPTS_COPY = {
  title: 'Guiones',
  subtitle: 'Crea y administra guiones para tus videos',
  new: 'Nuevo guion',
  emptyTitle: 'No hay guiones todavia',
  emptySubtitle: 'Escribe tu primer guion',
  create: 'Crear guion',
  edit: 'Editar',
  delete: 'Eliminar',
  deleteTitle: 'Eliminar guion',
  deleteWarning: 'Estas por eliminar',
  deleteIrreversible: 'Esta accion no se puede deshacer.',
  cancel: 'Cancelar',
  submitCreate: 'Crear guion',
  submitEdit: 'Guardar',
  submittingCreate: 'Creando...',
  submittingEdit: 'Guardando...',
  deleting: 'Eliminando...',
  wordCountLabel: 'palabras',
  ideaPrefix: 'De idea:',
  list: {
    showMore: 'Ver mas',
    showLess: 'Ver menos',
  },
  statuses: {
    draft: 'Borrador',
    review: 'En Revision',
    approved: 'Aprobado',
    recorded: 'Grabado',
  },
  fields: {
    title: 'Titulo',
    intro: 'Introduccion',
    body: 'Cuerpo',
    cta: 'Llamado a la accion',
    outro: 'Cierre',
  },
  placeholders: {
    title: 'Titulo del guion...',
    intro: 'Introduce el guion...',
    body: 'Desarrollo principal...',
    cta: 'Que accion quieres que tomen?',
    outro: 'Cierre y despedida...',
  },
  toasts: {
    created: 'Guion creado',
    updated: 'Guion actualizado',
    deleted: 'Guion eliminado',
    error: 'Error',
  },
  errors: {
    save: 'Error al guardar guion',
    delete: 'Error al eliminar guion',
  },
};
