import type { Locale } from '@/app/i18n/messages';

const SETTINGS_COPY_BY_LOCALE = {
  es: {
    title: 'Configuracion',
    subtitle: 'Administra tu cuenta personal de CronoStudio.',
    signedInAs: 'Sesion iniciada como',
    loadingProfile: 'Cargando perfil...',
    profile: {
      section: 'Perfil',
      helper: 'Administra tu nombre y correo.',
      name: 'Nombre',
      email: 'Correo',
      save: 'Guardar cambios',
      saved: 'Datos actualizados correctamente',
      loadError: 'No pudimos cargar tu perfil',
      loadErrorFallback: 'No pudimos obtener tu informacion. Intenta mas tarde.',
      saveError: 'No pudimos guardar los cambios',
      saveErrorFallback: 'Error al guardar el perfil',
    },
    preferences: {
      section: 'Preferencias',
      helper: 'Personaliza idioma y experiencia de tu cuenta.',
      language: 'Idioma de la app',
      languageEs: 'Espanol',
      languageEn: 'Ingles',
    },
    security: {
      section: 'Seguridad',
      currentPassword: 'Contrasena actual',
      newPassword: 'Nueva contrasena',
      confirmNew: 'Confirmar nueva',
      showCurrent: 'Mostrar contrasena actual',
      hideCurrent: 'Ocultar contrasena actual',
      showNew: 'Mostrar nueva contrasena',
      hideNew: 'Ocultar nueva contrasena',
      showConfirm: 'Mostrar confirmacion',
      hideConfirm: 'Ocultar confirmacion',
      updatePassword: 'Actualizar contrasena',
      mismatch: 'La confirmacion no coincide con la nueva contrasena',
      updated: 'Contrasena actualizada',
      updateError: 'No pudimos actualizar la contrasena',
    },
    oauth: {
      section: 'Integracion YouTube',
      helper: 'Configura credenciales OAuth propias para conectar el canal correcto.',
      loadError: 'No pudimos cargar la configuracion de YouTube',
      loadErrorFallback: 'No pudimos cargar la configuracion',
      source: 'Fuente:',
      sourceUser: 'configuracion personalizada',
      sourceEnv: 'variables del servidor',
      configured: 'Configurado',
      notConfigured: 'Sin configurar',
      recommended: 'Recomendado:',
      copy: 'Copiar',
      copyRedirectSuccess: 'Redirect URI copiado',
      copyRedirectError: 'No pudimos copiar el redirect URI',
      secretPlaceholderSaved: '•••••••• (guardado)',
      secretPlaceholderEmpty: 'Ingresa el secret',
      keepSecretHint: 'Si lo dejas vacio, se conserva el secret existente.',
      scopesHint: 'Separados por espacio o coma. Permitidos: youtube.readonly, yt-analytics.readonly.',
      save: 'Guardar configuracion',
      saveAndTest: 'Guardar y probar',
      preparing: 'Preparando...',
      saving: 'Guardando...',
      testing: 'Probando...',
      test: 'Probar conexion',
      resetServer: 'Restablecer a valores del servidor',
      saveSuccess: 'Configuracion guardada',
      saveError: 'No pudimos guardar la configuracion',
      deleteSuccess: 'Configuracion eliminada. Usando valores del servidor.',
      deleteError: 'No pudimos eliminar la configuracion',
      popupError: 'No se pudo abrir la ventana de Google. Revisa el bloqueador de popups.',
      connectSuccess: 'Conexion exitosa con YouTube',
      connectTimeout: 'No se pudo completar la conexion. Reintenta.',
    },
    team: {
      section: 'Equipo y colaboradores',
      helper: 'Invita colaboradores con acceso de lectura y edicion limitada.',
      helper2: 'El colaborador debe iniciar sesion con el correo invitado para aceptar.',
      emailPlaceholder: 'correo@dominio.com',
      creating: 'Creando...',
      createInvite: 'Crear invitacion',
      invalidEmail: 'Ingresa un correo valido',
      createError: 'No pudimos crear la invitacion',
      created: 'Invitacion creada',
      invitationLink: 'Link de invitacion',
      linkCopied: 'Link copiado',
      linkCopyError: 'No pudimos copiar el link',
      collaborators: 'Colaboradores',
      noCollaborators: 'Sin colaboradores.',
      invites: 'Invitaciones',
      noInvites: 'Sin invitaciones.',
    },
    recovery: {
      section: 'Recuperacion',
      helper: 'Perdiste el acceso? Podemos enviarte un enlace para restablecer la cuenta.',
      send: 'Enviar enlace de recuperacion',
      sent: 'Te enviamos un correo con instrucciones de recuperacion',
      sendError: 'No pudimos enviar el correo',
      sendErrorFallback: 'No pudimos enviar el correo de recuperacion',
    },
    session: {
      section: 'Sesion',
      helper: 'Gestiona tu acceso a CronoStudio desde aqui.',
      logout: 'Cerrar sesion',
    },
    danger: {
      section: 'Eliminar cuenta',
      helper: 'Esta accion eliminara todos tus datos. No se puede deshacer.',
      confirmLabel: 'Escribe ELIMINAR para confirmar',
      confirmWord: 'ELIMINAR',
      deleting: 'Eliminando...',
      delete: 'Eliminar mi cuenta',
      confirmError: 'Escribe ELIMINAR para confirmar',
      deleteError: 'No pudimos eliminar la cuenta',
    },
  },
  en: {
    title: 'Settings',
    subtitle: 'Manage your personal CronoStudio account.',
    signedInAs: 'Signed in as',
    loadingProfile: 'Loading profile...',
    profile: {
      section: 'Profile',
      helper: 'Manage your name and email.',
      name: 'Name',
      email: 'Email',
      save: 'Save changes',
      saved: 'Profile updated',
      loadError: 'Could not load your profile',
      loadErrorFallback: 'Could not fetch your information. Try again later.',
      saveError: 'Could not save changes',
      saveErrorFallback: 'Error saving profile',
    },
    preferences: {
      section: 'Preferences',
      helper: 'Customize language and account experience.',
      language: 'App language',
      languageEs: 'Spanish',
      languageEn: 'English',
    },
    security: {
      section: 'Security',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmNew: 'Confirm new',
      showCurrent: 'Show current password',
      hideCurrent: 'Hide current password',
      showNew: 'Show new password',
      hideNew: 'Hide new password',
      showConfirm: 'Show confirmation',
      hideConfirm: 'Hide confirmation',
      updatePassword: 'Update password',
      mismatch: 'Confirmation does not match new password',
      updated: 'Password updated',
      updateError: 'Could not update password',
    },
    oauth: {
      section: 'YouTube integration',
      helper: 'Configure your own OAuth credentials to connect the right channel.',
      loadError: 'Could not load YouTube configuration',
      loadErrorFallback: 'Could not load configuration',
      source: 'Source:',
      sourceUser: 'custom configuration',
      sourceEnv: 'server variables',
      configured: 'Configured',
      notConfigured: 'Not configured',
      recommended: 'Recommended:',
      copy: 'Copy',
      copyRedirectSuccess: 'Redirect URI copied',
      copyRedirectError: 'Could not copy redirect URI',
      secretPlaceholderSaved: '•••••••• (saved)',
      secretPlaceholderEmpty: 'Enter secret',
      keepSecretHint: 'If left empty, the existing secret is preserved.',
      scopesHint: 'Separated by spaces or commas. Allowed: youtube.readonly, yt-analytics.readonly.',
      save: 'Save configuration',
      saveAndTest: 'Save and test',
      preparing: 'Preparing...',
      saving: 'Saving...',
      testing: 'Testing...',
      test: 'Test connection',
      resetServer: 'Reset to server values',
      saveSuccess: 'Configuration saved',
      saveError: 'Could not save configuration',
      deleteSuccess: 'Configuration removed. Using server values.',
      deleteError: 'Could not remove configuration',
      popupError: 'Could not open Google window. Check popup blocker.',
      connectSuccess: 'Successful YouTube connection',
      connectTimeout: 'Could not complete connection. Retry.',
    },
    team: {
      section: 'Team and collaborators',
      helper: 'Invite collaborators with read and limited edit access.',
      helper2: 'Collaborator must sign in with the invited email to accept.',
      emailPlaceholder: 'email@domain.com',
      creating: 'Creating...',
      createInvite: 'Create invite',
      invalidEmail: 'Enter a valid email',
      createError: 'Could not create invite',
      created: 'Invite created',
      invitationLink: 'Invite link',
      linkCopied: 'Link copied',
      linkCopyError: 'Could not copy link',
      collaborators: 'Collaborators',
      noCollaborators: 'No collaborators.',
      invites: 'Invites',
      noInvites: 'No invites.',
    },
    recovery: {
      section: 'Recovery',
      helper: 'Lost access? We can send a reset link for your account.',
      send: 'Send recovery link',
      sent: 'We sent an email with recovery instructions',
      sendError: 'Could not send email',
      sendErrorFallback: 'Could not send recovery email',
    },
    session: {
      section: 'Session',
      helper: 'Manage your CronoStudio access from here.',
      logout: 'Log out',
    },
    danger: {
      section: 'Delete account',
      helper: 'This action will remove all your data. It cannot be undone.',
      confirmLabel: 'Type DELETE to confirm',
      confirmWord: 'DELETE',
      deleting: 'Deleting...',
      delete: 'Delete my account',
      confirmError: 'Type DELETE to confirm',
      deleteError: 'Could not delete account',
    },
  },
} as const;

export function getSettingsCopy(locale: Locale) {
  return SETTINGS_COPY_BY_LOCALE[locale] ?? SETTINGS_COPY_BY_LOCALE.es;
}
