import type { Locale } from '@/app/i18n/messages';

const AI_OUTPUT_COPY_BY_LOCALE = {
  es: {
    script: 'Guion',
    optimizedScript: 'Guion optimizado',
    proposedTitles: 'Titulos propuestos',
    noOutput: 'No hay salida para mostrar.',
    unsupportedOutput: 'Salida no compatible.',
    noInput: 'Sin input.',
    nicheRanking: 'Ranking de nichos',
    nicheFallback: 'Nicho',
    score: 'Score',
    risk: 'Riesgo',
    monetization: 'Monetizacion',
    contentClusters: 'Clusters de contenido',
    clusterFallback: 'Cluster',
    initialIdeas: 'Ideas iniciales',
    ideaFallback: 'Idea',
    angle: 'Angulo',
    hook: 'Hook',
    roadmap: 'Roadmap',
    phaseFallback: 'Fase',
    automation: 'Automatizacion',
    tools: 'Herramientas',
    workflow: 'Workflow',
    complianceAndRisk: 'Compliance y riesgo',
    actionPlan: 'Plan de accion',
    promise: 'Promesa',
    development: 'Desarrollo',
    turningPoint: 'Punto de inflexion',
    closing: 'Cierre',
    pacingNotes: 'Notas de ritmo',
    estimatedReduction: 'Reduccion estimada',
    changesMade: 'Cambios realizados',
    retentionBoosts: 'Refuerzos de retencion',
    thumbnailAngles: 'Angulos de miniatura',
    recommendedCombinations: 'Combinaciones recomendadas',
    emotion: 'Emocion',
    curiosity: 'Curiosidad',
  },
  en: {
    script: 'Script',
    optimizedScript: 'Optimized script',
    proposedTitles: 'Proposed titles',
    noOutput: 'No output to show.',
    unsupportedOutput: 'Unsupported output.',
    noInput: 'No input.',
    nicheRanking: 'Niche ranking',
    nicheFallback: 'Niche',
    score: 'Score',
    risk: 'Risk',
    monetization: 'Monetization',
    contentClusters: 'Content clusters',
    clusterFallback: 'Cluster',
    initialIdeas: 'Initial ideas',
    ideaFallback: 'Idea',
    angle: 'Angle',
    hook: 'Hook',
    roadmap: 'Roadmap',
    phaseFallback: 'Phase',
    automation: 'Automation',
    tools: 'Tools',
    workflow: 'Workflow',
    complianceAndRisk: 'Compliance and risk',
    actionPlan: 'Action plan',
    promise: 'Promise',
    development: 'Development',
    turningPoint: 'Turning point',
    closing: 'Closing',
    pacingNotes: 'Pacing notes',
    estimatedReduction: 'Estimated reduction',
    changesMade: 'Changes made',
    retentionBoosts: 'Retention boosts',
    thumbnailAngles: 'Thumbnail angles',
    recommendedCombinations: 'Recommended combinations',
    emotion: 'Emotion',
    curiosity: 'Curiosity',
  },
} as const;

export function getAiOutputCopy(locale: Locale) {
  return AI_OUTPUT_COPY_BY_LOCALE[locale] ?? AI_OUTPUT_COPY_BY_LOCALE.es;
}
