import type { Locale } from '@/app/i18n/messages';

const COMPONENT_COPY_BY_LOCALE = {
  es: {
    priorityActions: {
      title: 'Acciones pendientes',
      emptyTitle: 'Todo al dia',
      emptySubtitle: 'Sin pendientes por ahora',
      createTitle: 'Crear nuevo contenido',
      createSubtitle: 'Empieza aqui',
      goTo: 'Ir',
      itemsLabel: 'items',
      openAction: 'Abrir accion',
      createNewAria: 'Crear nuevo contenido',
    },
    productionsList: {
      emptyActive: 'Sin contenidos activos',
      emptyStage: 'Sin contenidos en esta etapa',
      changeFilter: 'Cambiar filtro ->',
      createFirst: 'Crear tu primer contenido ->',
      new: '+ Nuevo',
      reviewScript: 'Revisar guion',
      generateScript: 'Generar guion',
      seoTitles: 'SEO + Titulos',
      thumbnail: 'Miniatura',
      activeTitle: 'Contenidos activos',
      selectedCount: 'seleccionadas',
      recording: 'Grabacion',
      editing: 'Edicion',
      publish: 'Publicar',
      clear: 'Limpiar',
      createNewAria: 'Crear nuevo contenido',
      openContent: 'Abrir contenido',
      selectProduction: 'Seleccionar produccion',
      markPublished: 'Marcar como publicado',
    },
    automationRuns: {
      title: 'Automatizaciones',
      emptyTitle: 'Sin ejecuciones recientes',
      emptySubtitle: 'Los agentes estan listos',
      runsLabel: 'runs',
      now: 'ahora',
      minutesAgo: 'hace {n}m',
      hoursAgo: 'hace {n}h',
    },
    pipeline: {
      title: 'Pipeline de produccion',
      totalLabel: 'contenidos',
    },
    productionCard: {
      openProduction: 'Abrir produccion',
      detail: 'Ver detalle ->',
      labels: {
        idea: 'Idea',
        scripting: 'En guion',
        recording: 'Grabando',
        editing: 'Editando',
        shorts: 'Shorts',
        publishing: 'Publicando',
        published: 'Publicado',
      },
      progress: {
        script: 'Guion',
        thumbnail: 'Miniatura',
        seo: 'SEO',
        shorts: 'Shorts',
      },
    },
  },
  en: {
    priorityActions: {
      title: 'Pending actions',
      emptyTitle: 'All clear',
      emptySubtitle: 'No pending items for now',
      createTitle: 'Create new content',
      createSubtitle: 'Start here',
      goTo: 'Go',
      itemsLabel: 'items',
      openAction: 'Open action',
      createNewAria: 'Create new content',
    },
    productionsList: {
      emptyActive: 'No active content',
      emptyStage: 'No content in this stage',
      changeFilter: 'Change filter ->',
      createFirst: 'Create your first content ->',
      new: '+ New',
      reviewScript: 'Review script',
      generateScript: 'Generate script',
      seoTitles: 'SEO + Titles',
      thumbnail: 'Thumbnail',
      activeTitle: 'Active content',
      selectedCount: 'selected',
      recording: 'Recording',
      editing: 'Editing',
      publish: 'Publish',
      clear: 'Clear',
      createNewAria: 'Create new content',
      openContent: 'Open content',
      selectProduction: 'Select production',
      markPublished: 'Mark as published',
    },
    automationRuns: {
      title: 'Automations',
      emptyTitle: 'No recent runs',
      emptySubtitle: 'Agents are ready',
      runsLabel: 'runs',
      now: 'now',
      minutesAgo: '{n}m ago',
      hoursAgo: '{n}h ago',
    },
    pipeline: {
      title: 'Production pipeline',
      totalLabel: 'items',
    },
    productionCard: {
      openProduction: 'Open production',
      detail: 'View detail ->',
      labels: {
        idea: 'Idea',
        scripting: 'Scripting',
        recording: 'Recording',
        editing: 'Editing',
        shorts: 'Shorts',
        publishing: 'Publishing',
        published: 'Published',
      },
      progress: {
        script: 'Script',
        thumbnail: 'Thumbnail',
        seo: 'SEO',
        shorts: 'Shorts',
      },
    },
  },
} as const;

export function getComponentsCopy(locale: Locale) {
  return COMPONENT_COPY_BY_LOCALE[locale] ?? COMPONENT_COPY_BY_LOCALE.es;
}

export const COMPONENT_COPY = getComponentsCopy('es');
