import type { Locale } from '@/app/i18n/messages';

const DASHBOARD_COPY_BY_LOCALE = {
  es: {
    header: {
      tag: 'Control de produccion',
      title: 'Hoy en tu produccion',
      subtitle: 'Tu centro de comando para planificar, producir y publicar contenido con claridad.',
      newContent: 'Nuevo contenido',
    },
    loading: {
      dashboard: 'Cargando dashboard...',
    },
    summary: {
      title: 'Resumen',
      total: 'Total',
      totalSubtitle: 'Total en produccion',
      active: 'Activos',
      activeSubtitle: 'En curso',
      ideas: 'Ideas',
      ideasSubtitle: 'Ideas registradas',
      published: 'Publicados',
      publishedSubtitle: 'Publicado hasta hoy',
    },
    pipeline: {
      inStage: 'Contenidos en esta etapa',
      active: 'Contenidos activos',
      ideasActive: 'Ideas activas',
      noIdeas: 'No hay ideas activas.',
      ideasCountLabel: 'ideas',
    },
    priorityActions: {
      script: 'Continuar guion',
      thumbnail: 'Subir miniatura',
      seo: 'Optimizar SEO',
      shorts: 'Crear shorts',
    },
    calendar: {
      title: 'Calendario',
      subtitle: 'Programa publicaciones',
      month: 'Mes',
      week: 'Semana',
      schedule: 'Programar',
      selectContent: 'Selecciona contenido',
      scheduleAction: 'Programar publicacion',
      clear: 'Limpiar',
      agenda: 'Agenda',
      emptyDay: 'Sin publicaciones para este dia.',
      emptyUpcoming: 'Sin publicaciones programadas.',
      reschedule: 'Reprogramar',
      cancel: 'Cancelar',
      weekdays: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    },
    context: {
      title: 'Contexto',
      channel: 'Canal',
      selectChannel: 'Selecciona un canal',
      noChannels: 'Sin canales disponibles',
      isoWeek: 'Semana ISO',
      goal: 'Meta semanal',
      videos: 'videos',
      published: 'Publicados',
      defaultChannel: 'Canal por defecto',
    },
    social: {
      title: 'Redes sociales',
      connect: 'Conectar',
      items: [
        { name: 'Instagram', description: 'Reels, posts y stories' },
        { name: 'TikTok', description: 'Clips cortos y trends' },
        { name: 'LinkedIn', description: 'Posts, clips y branding' },
        { name: 'X', description: 'Hilos y anuncios' },
      ],
    },
    weeklyStatus: {
      title: 'Estado semanal',
      next: 'Proxima condicion critica',
      noNext: 'Semana completa o sin pendientes',
      channel: 'Canal',
    },
    weeklyStreak: {
      title: 'Indicador de ritmo',
      current: 'Racha actual',
      best: 'Mejor racha',
    },
    modal: {
      title: 'Nuevo contenido',
      placeholder: 'Titulo del contenido...',
      cancel: 'Cancelar',
      create: 'Crear contenido',
    },
    fab: {
      label: 'Nuevo',
    },
    toasts: {
      created: 'Contenido creado',
      createError: 'Error al crear contenido',
      createFailed: 'No se pudo crear contenido',
      scheduled: 'Publicacion programada',
      scheduleError: 'Error al programar publicacion',
      canceled: 'Publicacion cancelada',
      cancelError: 'Error al cancelar publicacion',
      sessionExpired: 'Sesion expirada. Inicia sesion nuevamente.',
      weeklyStatusError: 'Error al cargar estado semanal',
      publishMarked: 'Publicado',
      publishMarkError: 'Error al marcar como publicado',
      selectChannelFirst: 'Selecciona un canal primero',
      generatePlanError: 'Error al generar plan',
      planGenerated: 'Plan semanal generado',
      registerPublishError: 'Error al registrar publicacion',
      registerFromYoutubeSuccess: 'Publicacion registrada desde YouTube',
      updateProductionsError: 'Error al actualizar producciones',
      updateTargetDateError: 'Error al actualizar fecha objetivo',
      updatedProductions: 'Producciones actualizadas',
      updatedTargetDate: 'Fecha objetivo actualizada',
    },
    labels: {
      mondayShort: 'Lun',
      tuesdayShort: 'Mar',
      wednesdayShort: 'Mie',
      thursdayShort: 'Jue',
      fridayShort: 'Vie',
      saturdayShort: 'Sab',
      sundayShort: 'Dom',
      tuesday: 'Martes',
      friday: 'Viernes',
      pending: 'Pendiente',
      planned: 'Planificado',
      integrations: 'Integraciones',
      verifiedByYoutube: 'Verificado por YouTube',
      plan: 'Planificar',
      youtube: 'YouTube',
      planWeek: 'Planificar semana',
      verifyYoutube: 'Verificar YouTube',
      openInYoutube: 'Ver en YouTube',
      markAsPublished: 'Marcar como publicado',
      saveAsPublished: 'Marcar como publicado',
      saving: 'Guardando...',
      youtubeVideoId: 'YouTube videoId',
      noChannel: 'Sin canal',
      noDate: 'Sin fecha',
    },
    actions: {
      register: 'Registrar',
      plan: 'Planificar',
      createContent: 'Crear contenido',
      generateScript: 'Generar guion',
      generateSeo: 'Generar SEO',
      goToThumbnails: 'Ir a miniaturas',
      markPublished: 'Marcar publicado',
      generate: 'Generar',
      view: 'Ver',
      createIdea: 'Crear idea',
    },
    tabs: {
      production: 'Produccion',
      calendar: 'Calendario',
      backlog: 'Backlog',
    },
    cards: {
      weeklyAutoPlanTitle: 'Plan semanal automatico',
      weeklyAutoPlanSubtitle: '2 videos: Mar/Vie',
      weeklyAutoPlanGenerate: 'Generar plan semanal (2 videos: Mar/Vie)',
      weeklyAutoPlanGenerating: 'Generando...',
      firstStepsTitle: 'Primeros pasos recomendados',
      viewGuide: 'Ver guia',
      impactTitle: 'Impacto',
      impactSubtitle: 'Resumen de avance y valor generado.',
      impactPublished: 'Publicados',
      impactEstimatedSavings: 'Ahorro estimado',
      impactStreak: 'Racha',
      impactWeeks: 'semanas',
      kpisTitle: 'KPIs',
      kpisSubtitle: 'Conversion y cumplimiento semanal.',
      kpiIdeaToScript: 'Idea → Guion',
      kpiWeeklyCompletion: 'Cumplimiento semanal',
      kpiActive: 'Activas',
      thisWeek: 'Esta semana',
      weekLabelPrefix: 'Semana',
      publications: 'publicaciones',
      progress: 'Progreso',
      missing: 'Faltan',
      streak: 'Racha',
      best: 'Mejor',
      viewDetail: 'Ver detalle',
      hideFocus: 'Ocultar foco',
      showFocus: 'Mostrar foco',
      searchProduction: 'Buscar produccion',
      typeTitle: 'Escribe un titulo',
      clearSearch: 'Limpiar busqueda',
      nextStep: 'Proximo paso',
      noActiveProductionsYet: 'Aun no hay producciones activas.',
      openDetail: 'Abrir detalle',
      weeklyPlan: 'Plan semanal',
      goToCalendar: 'Ir a Calendario',
      shortcuts: 'Atajos',
      finalChecklist: 'Checklist final',
      status: 'Estado',
      targetDate: 'Fecha objetivo',
      updated: 'Actualizado',
      scriptReady: 'Guion listo',
      seoApproved: 'SEO aprobado',
      thumbnailApproved: 'Miniatura aprobada',
      published: 'Publicado',
      noActiveProductions: 'No hay producciones activas.',
      createProduction: 'Crear produccion',
      priority: 'Prioridad',
    },
    prompts: {
      scriptMissing: 'Falta guion para avanzar la produccion.',
      seoMissing: 'Falta SEO para preparar la publicacion.',
      thumbnailMissing: 'Falta miniatura aprobada.',
      readyToPublish: 'Listo para publicar. Registra el enlace.',
    },
    publishModal: {
      title: 'Marcar como publicado',
      helper: 'Pega la URL del video publicado para cerrar el pipeline y registrar el enlace.',
      missingSteps: 'Faltan pasos',
      publishedUrlLabel: 'URL publicado (opcional)',
      publishedUrlPlaceholder: 'https://youtube.com/watch?v=...',
      platformIdLabel: 'ID de plataforma (opcional)',
      cancel: 'Cancelar',
      confirm: 'Marcar como publicado',
    },
    drawer: {
      weeklyDetail: 'Detalle semanal',
      close: 'Cerrar',
      youtube: 'YouTube',
      openInYoutube: 'Ver en YouTube',
      noEvidence: 'Sin evidencia detectada',
      publishEvent: 'Publish event',
      registered: 'Registrado',
      noInternalRecord: 'Sin registro interno',
      registerOneClick: 'Registrar 1-click',
      registerManual: 'Registrar manual',
    },
    actionDock: {
      register: 'Registrar',
      plan: 'Planificar',
      youtube: 'YouTube',
      registerPublication: 'Registrar publicacion',
      planWeek: 'Planificar semana',
      verifyYoutube: 'Verificar YouTube',
    },
    common: {
      retry: 'Reintentar',
      guideMe: 'Guiame',
    },
    messages: {
      noActiveProductions: 'No hay producciones activas. Crea la primera para empezar el pipeline.',
      startCardHint: 'Conecta canal, genera ideas y arranca el pipeline.',
      weekEvaluationFailed: 'No se pudo evaluar la semana.',
      missingYoutubeRegistrations: 'Falta registrar publicaciones detectadas en YouTube',
      missingPublicationsPrefix: 'Falta',
      missingPublicationsSuffix: 'esta semana',
      publicationSingular: 'publicacion',
      publicationPlural: 'publicaciones',
      weekCompletedPlanNext: 'Semana completa. Planifica la proxima.',
    },
    reconcile: {
      authInvalid: 'YouTube necesita reautorizacion.',
      authInvalidAction: 'Reautorizar',
      refreshMissing: 'Falta refresh token. Reconecta YouTube.',
      refreshMissingAction: 'Reconectar',
      rateLimited: 'YouTube esta limitando. Reintenta en unos minutos.',
      unavailable: 'YouTube no responde ahora. Reintenta luego.',
      channelNotFound: 'No se encontro canal en YouTube para esta cuenta.',
      channelNotFoundAction: 'Revisar canal',
      generic: 'No se pudo verificar YouTube.',
      genericAction: 'Revisar integracion',
    },
    tour: {
      quickGuide: 'Guia rapida',
      back: 'Atras',
      close: 'Cerrar',
      next: 'Siguiente',
      finish: 'Finalizar',
      steps: [
        { id: 'week-stepper', title: 'Esta semana', description: 'Revisa Mar/Vie y el estado real del canal.' },
        { id: 'action-dock', title: 'Acciones rapidas', description: 'Registra, planifica o verifica YouTube en 1 clic.' },
        { id: 'pipeline', title: 'Produccion', description: 'Avanza por etapas sin perder el foco.' },
        { id: 'calendar', title: 'Calendario', description: 'Programa contenido y ajusta fechas.' },
        { id: 'integrations', title: 'Integraciones', description: 'Conecta canales y valida datos externos.' },
      ],
    },
    stageLabels: {
      idea: 'Ideas',
      scripting: 'Guiones',
      recording: 'Grabacion',
      editing: 'Edicion',
      shorts: 'Shorts',
      publishing: 'Publicacion',
      published: 'Publicado',
    },
  },
  en: {
    header: {
      tag: 'Production control',
      title: 'Today in your production',
      subtitle: 'Your command center to plan, produce, and publish content with clarity.',
      newContent: 'New content',
    },
    loading: {
      dashboard: 'Loading dashboard...',
    },
    summary: {
      title: 'Summary',
      total: 'Total',
      totalSubtitle: 'Total in production',
      active: 'Active',
      activeSubtitle: 'In progress',
      ideas: 'Ideas',
      ideasSubtitle: 'Registered ideas',
      published: 'Published',
      publishedSubtitle: 'Published to date',
    },
    pipeline: {
      inStage: 'Content in this stage',
      active: 'Active content',
      ideasActive: 'Active ideas',
      noIdeas: 'No active ideas.',
      ideasCountLabel: 'ideas',
    },
    priorityActions: {
      script: 'Continue script',
      thumbnail: 'Upload thumbnail',
      seo: 'Optimize SEO',
      shorts: 'Create shorts',
    },
    calendar: {
      title: 'Calendar',
      subtitle: 'Schedule publications',
      month: 'Month',
      week: 'Week',
      schedule: 'Schedule',
      selectContent: 'Select content',
      scheduleAction: 'Schedule publication',
      clear: 'Clear',
      agenda: 'Agenda',
      emptyDay: 'No publications for this day.',
      emptyUpcoming: 'No scheduled publications.',
      reschedule: 'Reschedule',
      cancel: 'Cancel',
      weekdays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    },
    context: {
      title: 'Context',
      channel: 'Channel',
      selectChannel: 'Select a channel',
      noChannels: 'No channels available',
      isoWeek: 'ISO Week',
      goal: 'Weekly goal',
      videos: 'videos',
      published: 'Published',
      defaultChannel: 'Default channel',
    },
    social: {
      title: 'Social media',
      connect: 'Connect',
      items: [
        { name: 'Instagram', description: 'Reels, posts, and stories' },
        { name: 'TikTok', description: 'Short clips and trends' },
        { name: 'LinkedIn', description: 'Posts, clips, and branding' },
        { name: 'X', description: 'Threads and announcements' },
      ],
    },
    weeklyStatus: {
      title: 'Weekly status',
      next: 'Next critical condition',
      noNext: 'Week complete or no pending items',
      channel: 'Channel',
    },
    weeklyStreak: {
      title: 'Pace indicator',
      current: 'Current streak',
      best: 'Best streak',
    },
    modal: {
      title: 'New content',
      placeholder: 'Content title...',
      cancel: 'Cancel',
      create: 'Create content',
    },
    fab: {
      label: 'New',
    },
    toasts: {
      created: 'Content created',
      createError: 'Error creating content',
      createFailed: 'Unable to create content',
      scheduled: 'Publication scheduled',
      scheduleError: 'Error scheduling publication',
      canceled: 'Publication canceled',
      cancelError: 'Error canceling publication',
      sessionExpired: 'Session expired. Sign in again.',
      weeklyStatusError: 'Error loading weekly status',
      publishMarked: 'Published',
      publishMarkError: 'Error marking as published',
      selectChannelFirst: 'Select a channel first',
      generatePlanError: 'Error generating weekly plan',
      planGenerated: 'Weekly plan generated',
      registerPublishError: 'Error registering publication',
      registerFromYoutubeSuccess: 'Publication registered from YouTube',
      updateProductionsError: 'Error updating productions',
      updateTargetDateError: 'Error updating target date',
      updatedProductions: 'Productions updated',
      updatedTargetDate: 'Target date updated',
    },
    labels: {
      mondayShort: 'Mon',
      tuesdayShort: 'Tue',
      wednesdayShort: 'Wed',
      thursdayShort: 'Thu',
      fridayShort: 'Fri',
      saturdayShort: 'Sat',
      sundayShort: 'Sun',
      tuesday: 'Tuesday',
      friday: 'Friday',
      pending: 'Pending',
      planned: 'Planned',
      integrations: 'Integrations',
      verifiedByYoutube: 'Verified by YouTube',
      plan: 'Plan',
      youtube: 'YouTube',
      planWeek: 'Plan week',
      verifyYoutube: 'Verify YouTube',
      openInYoutube: 'Open in YouTube',
      markAsPublished: 'Mark as published',
      saveAsPublished: 'Mark as published',
      saving: 'Saving...',
      youtubeVideoId: 'YouTube videoId',
      noChannel: 'No channel',
      noDate: 'No date',
    },
    actions: {
      register: 'Register',
      plan: 'Plan',
      createContent: 'Create content',
      generateScript: 'Generate script',
      generateSeo: 'Generate SEO',
      goToThumbnails: 'Go to thumbnails',
      markPublished: 'Mark published',
      generate: 'Generate',
      view: 'View',
      createIdea: 'Create idea',
    },
    tabs: {
      production: 'Production',
      calendar: 'Calendar',
      backlog: 'Backlog',
    },
    cards: {
      weeklyAutoPlanTitle: 'Automatic weekly plan',
      weeklyAutoPlanSubtitle: '2 videos: Tue/Fri',
      weeklyAutoPlanGenerate: 'Generate weekly plan (2 videos: Tue/Fri)',
      weeklyAutoPlanGenerating: 'Generating...',
      firstStepsTitle: 'Recommended first steps',
      viewGuide: 'View guide',
      impactTitle: 'Impact',
      impactSubtitle: 'Progress and generated value summary.',
      impactPublished: 'Published',
      impactEstimatedSavings: 'Estimated savings',
      impactStreak: 'Streak',
      impactWeeks: 'weeks',
      kpisTitle: 'KPIs',
      kpisSubtitle: 'Conversion and weekly compliance.',
      kpiIdeaToScript: 'Idea -> Script',
      kpiWeeklyCompletion: 'Weekly completion',
      kpiActive: 'Active',
      thisWeek: 'This week',
      weekLabelPrefix: 'Week',
      publications: 'publications',
      progress: 'Progress',
      missing: 'Missing',
      streak: 'Streak',
      best: 'Best',
      viewDetail: 'View detail',
      hideFocus: 'Hide focus',
      showFocus: 'Show focus',
      searchProduction: 'Search production',
      typeTitle: 'Type a title',
      clearSearch: 'Clear search',
      nextStep: 'Next step',
      noActiveProductionsYet: 'There are no active productions yet.',
      openDetail: 'Open detail',
      weeklyPlan: 'Weekly plan',
      goToCalendar: 'Go to Calendar',
      shortcuts: 'Shortcuts',
      finalChecklist: 'Final checklist',
      status: 'Status',
      targetDate: 'Target date',
      updated: 'Updated',
      scriptReady: 'Script ready',
      seoApproved: 'SEO approved',
      thumbnailApproved: 'Thumbnail approved',
      published: 'Published',
      noActiveProductions: 'No active productions.',
      createProduction: 'Create production',
      priority: 'Priority',
    },
    prompts: {
      scriptMissing: 'A script is missing to move production forward.',
      seoMissing: 'SEO is missing to prepare publication.',
      thumbnailMissing: 'An approved thumbnail is missing.',
      readyToPublish: 'Ready to publish. Register the link.',
    },
    publishModal: {
      title: 'Mark as published',
      helper: 'Paste the published video URL to close the pipeline and register the link.',
      missingSteps: 'Missing steps',
      publishedUrlLabel: 'Published URL (optional)',
      publishedUrlPlaceholder: 'https://youtube.com/watch?v=...',
      platformIdLabel: 'Platform ID (optional)',
      cancel: 'Cancel',
      confirm: 'Mark as published',
    },
    drawer: {
      weeklyDetail: 'Weekly detail',
      close: 'Close',
      youtube: 'YouTube',
      openInYoutube: 'Open in YouTube',
      noEvidence: 'No evidence detected',
      publishEvent: 'Publish event',
      registered: 'Registered',
      noInternalRecord: 'No internal record',
      registerOneClick: 'Register 1-click',
      registerManual: 'Register manually',
    },
    actionDock: {
      register: 'Register',
      plan: 'Plan',
      youtube: 'YouTube',
      registerPublication: 'Register publication',
      planWeek: 'Plan week',
      verifyYoutube: 'Verify YouTube',
    },
    common: {
      retry: 'Retry',
      guideMe: 'Guide me',
    },
    messages: {
      noActiveProductions: 'No active productions. Create the first one to start the pipeline.',
      startCardHint: 'Connect a channel, generate ideas, and start the pipeline.',
      weekEvaluationFailed: 'Could not evaluate the week.',
      missingYoutubeRegistrations: 'Missing registration for publications detected on YouTube',
      missingPublicationsPrefix: 'Missing',
      missingPublicationsSuffix: 'this week',
      publicationSingular: 'publication',
      publicationPlural: 'publications',
      weekCompletedPlanNext: 'Week complete. Plan the next one.',
    },
    reconcile: {
      authInvalid: 'YouTube needs reauthorization.',
      authInvalidAction: 'Reauthorize',
      refreshMissing: 'Missing refresh token. Reconnect YouTube.',
      refreshMissingAction: 'Reconnect',
      rateLimited: 'YouTube is rate limiting. Try again in a few minutes.',
      unavailable: 'YouTube is currently unavailable. Try again later.',
      channelNotFound: 'No YouTube channel found for this account.',
      channelNotFoundAction: 'Review channel',
      generic: 'Could not verify YouTube.',
      genericAction: 'Review integration',
    },
    tour: {
      quickGuide: 'Quick guide',
      back: 'Back',
      close: 'Close',
      next: 'Next',
      finish: 'Finish',
      steps: [
        { id: 'week-stepper', title: 'This week', description: 'Review Tue/Fri and the real channel status.' },
        { id: 'action-dock', title: 'Quick actions', description: 'Register, plan, or verify YouTube in one click.' },
        { id: 'pipeline', title: 'Production', description: 'Move through stages without losing focus.' },
        { id: 'calendar', title: 'Calendar', description: 'Schedule content and adjust dates.' },
        { id: 'integrations', title: 'Integrations', description: 'Connect channels and validate external data.' },
      ],
    },
    stageLabels: {
      idea: 'Ideas',
      scripting: 'Scripts',
      recording: 'Recording',
      editing: 'Editing',
      shorts: 'Shorts',
      publishing: 'Publishing',
      published: 'Published',
    },
  },
} as const;

export function getDashboardCopy(locale: Locale) {
  return DASHBOARD_COPY_BY_LOCALE[locale] ?? DASHBOARD_COPY_BY_LOCALE.es;
}

export function getStageLabels(locale: Locale) {
  return getDashboardCopy(locale).stageLabels;
}

export const DASHBOARD_COPY = getDashboardCopy('es');
export const STAGE_LABELS = getStageLabels('es');
