import type { PendingActionType, PipelineStage, ProductionStatus, IdeaStatus } from '@/domain/types';
import type { CalendarItemType } from '@/domain/types/calendar';

export const UI_COPY = {
  metadata: {
    title: 'CronoStudio - YouTube Analytics Dashboard',
    description: 'Gestiona y automatiza tus canales de YouTube',
  },
  dashboard: {
    kicker: 'Control de produccion',
    title: 'Hoy en tu produccion',
    description: 'Tu centro de comando para planificar, producir y publicar contenido con claridad.',
    createLabel: 'Nuevo contenido',
    createPlaceholder: 'Título del contenido',
    createShortLabel: 'Nuevo',
    creatingLabel: 'Creando...',
    loading: 'Cargando dashboard...',
    filters: {
      stagePrefix: 'Filtrando por',
      clearStage: 'Quitar filtro',
    },
    sections: {
      pipeline: 'Pipeline de produccion',
      pending: 'Acciones pendientes',
      active: 'Contenidos activos',
      runs: 'Ejecuciones recientes',
      social: 'Redes sociales',
      summary: 'Resumen',
    },
  },
  navigation: {
    dashboard: 'Dashboard',
    ideas: 'Ideas',
    scripts: 'Guiones',
    thumbnails: 'Miniaturas',
    seo: 'SEO',
    channels: 'Canales',
    analytics: 'Analítica',
    calendar: 'Calendario',
  },
  auth: {
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Salir',
    accountLabel: 'Mi cuenta',
  },
  common: {
    cancel: 'Cancelar',
  },
  pendingActions: {
    itemsLabel: 'items',
    emptyTitle: '¡Todo al día!',
    emptyDescription: 'Usa “Nuevo contenido” para comenzar.',
    emptyAction: 'Nuevo contenido',
    primaryLabels: {
      script: 'Continuar',
      seo: 'Optimizar',
      thumbnail: 'Abrir',
      short: 'Abrir',
      publish: 'Programar',
    } satisfies Record<PendingActionType, string>,
    secondaryLabels: {
      pipeline: 'Ver en pipeline',
      section: 'Ir a sección',
    },
  },
  productions: {
    emptyTitle: 'Sin contenidos activos',
    emptyDescription: 'Usa “Nuevo contenido” para comenzar.',
    openLabel: 'Abrir contenido',
  },
  automationRuns: {
    title: 'Automatizaciones',
    itemsLabel: 'runs',
    emptyTitle: 'Sin ejecuciones recientes',
    emptyDescription: 'Los agentes están listos',
    statusLabels: {
      running: 'En progreso',
      completed: 'Completado',
      error: 'Error',
    },
    time: {
      now: 'ahora',
      minutesAgo: 'hace {minutes}m',
      hoursAgo: 'hace {hours}h',
    },
  },
  pipeline: {
    totalLabel: 'contenidos',
    stages: {
      idea: 'Ideas',
      scripting: 'Guion',
      recording: 'Grabacion',
      editing: 'Edicion',
      shorts: 'Shorts',
      publishing: 'Publicar',
      published: 'Publicado',
    } satisfies Record<PipelineStage, string>,
  },
  ideas: {
    title: 'Ideas',
    description: 'Apunta y gestiona tus ideas para videos',
    createLabel: 'Nueva Idea',
    emptyTitle: 'No hay ideas todavia',
    emptyDescription: 'Apunta tu primera idea para un video.',
    form: {
      titleLabel: 'Título',
      descriptionLabel: 'Descripción',
      priorityLabel: 'Prioridad (0-10)',
      create: 'Crear Idea',
      creating: 'Creando...',
      cancel: 'Cancelar',
      submitError: 'Error al crear idea',
    },
    edit: {
      editLabel: 'Editar',
      saveLabel: 'Guardar',
      cancelLabel: 'Cancelar',
      requiredTitle: 'El título es obligatorio',
      updateError: 'Error al actualizar idea',
      successLabel: 'Cambios guardados',
    },
    delete: {
      label: 'Eliminar',
      title: 'Eliminar idea',
      confirm: '¿Seguro que quieres eliminar',
      confirmSuffix: 'Esta acción no se puede deshacer.',
      deleting: 'Eliminando...',
    },
    statusLabels: {
      draft: 'Borrador',
      approved: 'Aprobada',
      in_production: 'En Producción',
      completed: 'Completada',
      archived: 'Archivada',
    } satisfies Record<IdeaStatus, string>,
  },
  errors: {
    fallbackTitle: 'Algo salió mal',
    fallbackDescription: 'Intenta recargar la página.',
    reload: 'Recargar',
  },
  productionStatusLabels: {
    idea: 'Idea',
    scripting: 'Guion',
    recording: 'Grabando',
    editing: 'Editando',
    shorts: 'Shorts',
    publishing: 'Publicando',
    published: 'Publicado',
  } satisfies Record<ProductionStatus, string>,
  productionDetail: {
    titlePrefix: 'Producción',
    statusLabel: 'Estado',
    actions: {
      viewPipeline: 'Ver en pipeline',
      viewSection: 'Ir a sección',
    },
    links: {
      scripts: 'Guiones',
      thumbnails: 'Miniaturas',
      seo: 'SEO',
      videos: 'Videos',
    },
  },
  pendingActionTitles: {
    script: 'Continuar guión',
    seo: 'Optimizar SEO',
    thumbnail: 'Subir miniatura',
    short: 'Crear shorts',
    publish: 'Programar publicación',
  } satisfies Record<PendingActionType, string>,
  nextActionLabels: {
    idea: 'Empezar guión',
    scripting: 'Continuar guión',
    recording: 'Subir grabación',
    editing: 'Terminar edición',
    shorts: 'Crear shorts',
    publishing: 'Programar publicación',
    published: 'Ver detalles',
  } satisfies Record<ProductionStatus, string>,
  social: {
    instagram: {
      label: 'Instagram',
      description: 'Reels, posts y stories',
      action: 'Conectar',
    },
    tiktok: {
      label: 'TikTok',
      description: 'Clips cortos y trends',
      action: 'Conectar',
    },
    linkedin: {
      label: 'LinkedIn',
      description: 'Posts, clips y branding',
      action: 'Conectar',
    },
  },
  summary: {
    total: 'Total',
    active: 'Activos',
    ideas: 'Ideas',
    published: 'Publicados',
    totalHint: '+2 esta semana',
    activeHint: 'Prioridad alta',
    ideasHint: '+3 nuevas',
    publishedHint: 'Meta semanal',
  },
  calendar: {
    title: 'Calendario',
    description: 'Planifica qué publicar y cuándo, con foco en los próximos días.',
    monthLabel: 'Mes',
    rangeLabel: 'Rango',
    controls: {
      previousMonth: 'Mes anterior',
      nextMonth: 'Mes siguiente',
    },
    rangeOptions: {
      thirty: '30 días',
      sixty: '60 días',
      ninety: '90 días',
    },
    emptyTitle: 'Sin publicaciones programadas',
    emptyDescription: 'Cuando agendes contenido aparecerá aquí.',
    upcomingTitle: 'Próximos contenidos',
    dayLabel: 'Día',
    typeLabels: {
      production: 'Producción',
      short: 'Short',
      social: 'Social',
    } satisfies Record<CalendarItemType, string>,
    statusLabel: 'Estado',
    filterLabel: 'Filtrar por tipo',
    filterAll: 'Todos',
    viewLabels: {
      month: 'Mes',
      list: 'Lista',
    },
  },
} as const;
